import Head from 'next/head';
import { generateMonth } from '@/utils/calendar-gen';

function DayNames() {
  return (
    <div className={'grid grid-cols-7'}>
      {['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(
        (dayName, i) => (
          <div
            key={`${dayName}${i}`}
            className={'flex justify-center items-center w-16 h-16 bg-blue-300 border border-blue-300'}
            >
            {dayName}
          </div>
        ),
      )}
    </div>
  );
}

export default function Calendar() {
  const data = generateMonth();
  return (
    <div >
      <Head>
        <title>Next-Calendar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <h1 className={'test'} >
          Hello world!
        </h1>
        <div className={'box-border flex m-8 bg-white'}>
          <div className={'rounded-md border'}>
            <DayNames/>
            <pre>
              {JSON.stringify(data(), null, 2)}
            </pre>
          </div>
        </div>
      </main>
    </div>
  );
}
